version: "3.3"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - type: "bind"
        source: "/Users/fs/Personal/DevProjects/ScratchDetect/notebooks"
        target: "/home/jovyan"

